# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'wtriviaf' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wtriviaf

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # react-native-google-signin
  pod 'GoogleSignIn'

end
